### PR TITLE
Upgrade to LTS node version

### PR DESCRIPTION
**Pull request by MoLow**

### CODE REVIEW

**Comment by AntonIndrawan-TomTom** [comment]
@thehanimo : Can this PR be merged?

**Comment by antonindrawan** [comment]
Upvote! @thehanimo Can this PR be merged?

**Comment by thehanimo** [comment]
Thanks @MoLow @antonindrawan! Will release a new version soon.

**Comment by thehanimo** [comment]
Released [v1.4.2](https://github.com/thehanimo/pr-title-checker/releases/tag/v1.4.2)!

**Pull request merged**
