### PR TITLE
use typescript for main action file; add option to use local filepaths

### PR DESCRIPTION
**Pull request by smzelek**
hi! I'm happy to change anything here

my team had a need to use a predownloaded, local filepath (instead of one that was hosted in the same repo).

while I was at it I changed this to use TypeScript.

I just wanted to offer up this PR as a starting point for conversation; let me know if you're super opposed to this

### CODE REVIEW

**Comment by thehanimo** [comment]
This is great! Typescript also seems to package the action really well. When you say local filepath, was this present in the same repo that the action's code is in? This will be useful if this repo is forked, a config is added into that fork, and any repo could then use that action (from the fork) with the pre-defined config in it, correct?

**Comment by smzelek** [comment]
@thehanimo 

At my company we use an action in a previous step to pull a file from a private repo shared across the organization, so that we can reuse the same config file for the PR Title Checker action across all of our team's repos.

But the config file could also be local to the repo running the action, correct!

**Comment by smzelek** [comment]
```
name: Enforce PR Titles

on:
  workflow_call:

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with config file
        uses: actions/checkout@v3
        with:
          repository: ...
          ref: v4
          ssh-key: ${{ secrets.... }}
          path: .github/actions
      - name: Enforce PR Title
        uses: smzelek/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/actions/enforce-pr-titles/config.json"
          use_local_configuration_file: true
```

**Comment by thehanimo** [comment]
I do not want to make changes to your main branch since you may be using it in your repos. I will merge this into dev and add support for external links (#28) and make a few changes.

**Pull request merged**
